# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dhcli < Formula
  desc "A command-line tool for DigitalHub platform."
  homepage "https://scc-digitalhub.github.io/"
  version "0.10.1"

  on_macos do
    url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.10.1/dhcli-darwin.tar.gz"
    sha256 "20a60e2ab0ce48db3cb723bb67854d5f8ecf640a72daf3aacc75f5cea986eb30"

    def install
      bin.install "dhcli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.10.1/dhcli-linux-amd64.tar.gz"
        sha256 "e8db5285149d3ced7c6e22a5c839c320b908dee3b1db259f6ceb376e9ab7f6a0"

        def install
          bin.install "dhcli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/scc-digitalhub/digitalhub-cli/releases/download/0.10.1/dhcli-linux-arm64.tar.gz"
        sha256 "b5e1269eda2d4c455dc4093af06bf5521e75a00c1d066c806bdf46f6dc792314"

        def install
          bin.install "dhcli"
        end
      end
    end
  end
end
